const config = {
    "offlinemodus": false, 
    "bildschirmschoner": true, 
    "tagesabrechnung": false, 
    "tageszusammenfassung": false, 
    "kundentagesübersicht": false, 
    "preisanpassungessen": true, 
    "sanduhr": 5, 
    "cc_guest": "Gast",
    "cc_member":  "Mitglied", 
    "cc_seller": "Café Lüsse", 
    "cc_admin": "Fridgekeeper", 
    "Vereinsname": "Flugsportclub Charlottenburg Berlin e.V.", 
    "VereinsnameAbk": "FCC Berlin", 
    "Kassenwart": "Ronald Liepold", 
    "Straße": "Lüsse 14A",
    "PLZ": "14806",
    "Ort": "Bad Belzig",
    "Telefon": "+49 33841 30770",
    "Email": "kontakt@fccberlin.de",
    "Webseite": "fccberlin.de",
    "Bankverbindung": "n.n.",
    "IBAN": "n.n.",
    "BIC": "n.n.",
    "Kontoinhaber": "n.n.",
    "Steuernummer": "n.n.",
    "UStID": "n.n."
}